
var questions_by_topic = {
  "Generic": [
    "If you could be any animal what would it be and why?",
    "What is one of the things you would put on your 'bucket' list?",
    "Who is your favorite super hero and why?",
    "Who do you admire the most?",
    "What is your favorite summer activity?",
    "If a movie was made of your life what genre would it be, who would play you?",
    "If you could be any flavor of ice cream what ice cream flavor would you be and why?",
    "Who is your favorite cartoon character and why?",
    "If you could go any where in the world where would you go and why?",
    "What is your dream job?",
    "Are you a morning or a night person?",
    "What is your favorite hobby?",
    "What is one thing that annoys you the most?",
    "What is the strangest thing you have ever eaten?",
    "What is your favorite thing about someone in your family?",
    "What is one of your weird quirks?",
    "Describe your self in 3 words.",
    "If you could trade lives with anyone for a day who would it be and why?",
    "If you could talk in your sleep what would you say?",
    "What is the first thing you do when you get up in the morning?",
    "What is your favorite movie quote?",
    "What is your favorite joke?",
  ],

  "Good": [
    "What would you do on Mars for fun?",
    "If you could get yourself anything, what would you get?",
    "Where is the worst place you could get stuck?",
    "What would you do with your '15 minutes' of fame?",
    "Where would you go if you where invisible?",
    "What is your favorite flavor of 'Berty Bots every flavored beans'.",
    "What is the one thing you own you wish you didn’t?",
    "Describe the perfect kiss in 3 words.",
    "What is your biggest addiction?",
    "Do you have a song that reminds you of a relationship if so what song?",
    "How many books have you read so far this year?",
    "When I dance, I look like…?",
    "Who have you met that you wish you hadn’t?",
    "If you were famous what would you be famous for?",
    "What is the worst job you could have?",
    "What is your favorite T.V. channel?",
    "What is the thing your most afraid of?",
    "If you could paint anything what would you paint?",
    "What celebrity annoys you the most?",
    "What is the most interesting thing you have in your purse/wallet?",
    "What is the meanest thing you’ve ever said to someone?",
  ],

  "Best": [
    "If you could get a yacht what would you call it?",
    "What is your life long dream?",
    "If you could talk to the President what would you talk about?",
    "Have you ever tried to do something you know you would be really bad at, what was it?",
    "On a scale of 1 to 10 how 'cool' are you?",
    "What is the best advantage to being really tall?",
    "How long does it take you to get ready in the morning?",
    "What is the one thing you have always wanted to do?",
    "What TV sitcom family would you be a member of?",
    "What store do you shop at the most?",
    "What new technology will transform the future?",
    "What supply in your house is running low?",
    "If you could be any nationality what would it be?",
    "What is the most delightful word you can think of?",
    "What is your least favorite beverage?",
    "What is the first thing you notice about the opposite sex?",
    "If you were stranded on a tropical island what 2 things would you want with you?",
    "What is the first thing you notice about someone when you first meet?",
    "If you where running for office what would your campaign slogan be?",
    "What was your favorite book growing up?",
    "What city in America should not be included on a map, why?",
    "What compliment does people give you the most?",
  ],

  "Random": [
    "Nickname?",
    "Sub or dom?",
    "What is your best childhood memory?",
    "Favorite color?",
    "Are you single?",
    "What do you think of when I say, 'fruit'?",
    "Do you always wear your seat belt?",
    "Have you been in a car accident?",
    "Any pet peeves?",
    "Work out preferences?",
    "Favorite flower?",
    "Last band or artist you listened to?",
    "How did that particular song make you feel?",
    "Bed size?",
    "Do anything spontaneous lately?",
    "Like your job?",
    "Last person you went to dinner with?",
    "What are you currently learning?",
    "What do you think of people with tattoos?",
    "Coffee?",
    "Has your world ever been rocked?",
  ],

  "Rapid": [,
    "What word would you add to the dictionary if you could, what would it mean?",
    "What product would you refuse to promote?",
    "What is your favorite pet’s name?",
    "Use one word to describe your computer ability?",
    "If your plane was about to crash, who would you want sitting next to you?",
    "Which of the presidents was your favorite?",
    "How long of a consecutive time have you spent in a car?",
    "What is your favorite Halloween costume?",
    "How can you tell if some one is a nerd?",
    "If you could teach any grade or subject what would it be?",
    "If you could choose your nickname what would it be?",
    "What is your best feature?",
    "If you could swim in any liquid what would it be and why?",
    "What is the song you hear most often?",
    "What have you done that you are most proud of?",
    "How many keys do you have on your key ring?",
    "What is your favorite song?",
    "How old where you when you had the worst hair cut ever what style was it?",
    "What advice did you get that was the most rewarding?",
    "If you could change one thing about your looks what would it be?",
    "What is your least favorite type of music?",
    "If you where a super hero what would your powers be?",
    "What fortune would you want to get from a fortune cookie?",
  ],

  "Rapid-friends": [
    "What is one food you wouldn’t want to give up?",
    "If you won a million dollars what would you buy?",
    "If you had access to a time machine where and when would you go?",
    "If you could add a person to Mount Rushmore who would it be, why?",
    "If you could win any award what would it be, why?",
    "If you could teleport, where would you go, why?",
    "What was your favorite cartoon show growing up?",
    "Morning, noon or night?",
    "How do you like your steak cooked?",
    "What was the last film you watched?",
    "What is your favorite place to watch TV?",
    "If you could live anywhere in the world, where would it be?",
    "What did you eat for breakfast?",
    "What is your favorite cuisine?",
    "What foods do you dislike?",
    "What is your dream car?",
    "What are your favorite clothes?",
    "Where would you visit, if you had the chance?",
    "Weapon of choice?",
    "Where would you want to retire?",
    "Gold or silver?",
    "Where were you born?",
    "What is your favorite sport to watch?",
    "What is the last thing you liked on social media?",
    "Underwear?",
    "Hard of soft?",
    "Do you have any pets?",
    "Are you a morning or a night person?",
  ],

  "Rapid-couples": [
    "Have you ever been in love?",
    "What is success?",
    "What secret would you like to tell me?",
    "How do you define happiness?",
    "What is one item you could NEVER live without?",
    "Sunset?",
    "Favorite place to hideout?",
    "Leader or follower?",
    "Last time you were emotional?",
    "What makes your smile?",
    "Naked?",
    "What makes you angry?",
    "Sunrise?",
    "Chocolate or caramel?",
    "What impresses you?",
    "Where were you two years ago?",
    "What makes you feel sad?",
    "Where will you be in three-years?",
    "Red or Blue?",
    "What annoys you?",
    "What are you afraid of?",
    "What time did you go to bed last night?",
    "Who do you kiss last?",
    "Wifi?",
    "Fast or slow?",
    "What time will you go to bed tonight?",
    "Are you a dog or cat person?",
    "Cold or hot?",
    "What is better: certificates or experience?",
    "Mother or father?",
    "Wet or dry?",
    "Quality of life or quantity of life?",
    "America?",
    "If you had to choose a perpetually cold or hot place to live, what would you choose?",
    "Tell me how far away you live?",
    "Money?",
    "What is better: being organized or attention to details?",
    "Politics?",
    "Last time you laughed very hard out loud?",
    "Two things you would change about yourself?",
    "Your 20s?",
    "Naver or Google?",
    "When are you most productive?",
    "What chore do you hate doing?",
    "What motivates you?",
    "Kpop or Hip-hop?",
    "Last person you touched?",
  ],

  "Rapid-boys": [,
    "Which historical figure wins the award for being most hardcore?",
    "What issue do most people think is black and white but you think there is a lot nuance to?",
    "If you have children what career do you hope they peruse and what career would you never want them to get into?",
    "What is your dream job and what makes it so amazing?",
    "What event in your life would make a good movie?",
    "What job would you be absolutely horrible at?",
    "What movie has everyone else seen but you haven’t?",
    "What is the next big thing?",
    "What commercial convinced you NOT to buy the product they are pushing?",
    "What is the most useless major in college?",
    "What is something most people do easily but you find very difficult?",
    "What job doesn't exist but should?",
    "What TV news story is getting more attention than it should?",
    "What is the most impressive thing you know how to do?",
  ],

  "Rapid-girls": [
    "What is the ugliest vegetable?",
    "What product would you seriously stockpile if you found out they weren’t going to sell it anymore?",
    "What is the absolute worst movie you have ever seen?",
    "What food do you crave most often?",
    "What is the grossest sounding English word?",
    "What silliest thing you get nostalgic for?",
    "When is lying the right thing to do?",
    "What is your version of “There’s two types of people in this world…”?",
    "If you could only eat one food for the rest of your life, what would it be?",
    "What is your dream car?",
    "If you opened a restaurant, what kind of restaurant would it be?",
    "What quote do you (try to) live by?",
    "What is your hometown famous for?",
    "Do you think the world would be a better or worse place if everyone suddenly could read each other’s thoughts?",
    "If you lived in a tribal society, what role would you play? (Hunter, gatherer, shaman, chieftain, etc.)",
    "Which appliance can you not live without?",
    "Whose advice do you always listen to?",
    "Would you go to another planet even if it meant that you would never return to earth and eventually die on that planet?",
  ],

  "Rapid-flirty": [
    "What did you first think of me?",
    "Who is your celebrity crush?",
    "Would you rather be considered sexy or smart?",
    "Who do you think should make the first move?",
    "Guys or girls?",
    "How would you describe yourself in 3 words?",
    "Okay, now how would you describe me in 3 words?",
    "What is your favorite feature on a guy/girl?",
    "Do you find tattoos sexy?",
    "Do you prefer a pool or a hot tub?",
    "Would you prefer to make out or cuddle? Or make out, then cuddle?",
  ],

  "Rapid-bestfriend": [
    "How many times have you fallen in love?",
    "What inspires you the most?",
    "If you needed one, what would your DJ name be?",
    "On your first day as President, what would you do?",
    "Favorite I-only-listen-to-this-in-the-car-when-I’m-very-much-alone song?",
    "What makes you cry?",
    "If you HAD to change your name, what would you change it to?",
    "What is been your greatest achievement (so far)?",
    "Which emoji would best capture your essence?",
    "Pizza or grilled cheese —be real with me.",
    "What is your favorite constellation?",
    "Which X-Men superpowers would you want?",
    "What is your favorite punctuation mark?",
    "Most valuable high-school or college class you ever took?",
    "Whose fictional wardrobe do you want most?",
    "What makes you feel nostalgic?",
    "Who was your embarrassing 2000s celeb crush?",
    "What would the title of your memoir be?",
    "What are the saddest, most beautiful lyrics you’ve ever heard?",
    "Have you overcome one of your fears?",
    "Super fuzzy socks or Uggs?",
    "What is the most embarrassing trend you gave in to?",
    "What are you most proud of?",
    "Favorite movie or TV show soundtrack?",
    "Do you believe in ghosts?",
    "When you eat a pack of Skittles, do you save the best flavors for last? Or do they go first?" ,
  ]
}