const babyNames = [
    { id: 1, name: 'Sofia', description: 'Wisdom' },
    { id: 2, name: 'Luca', description: 'Light' },
    { id: 3, name: 'Mateo', description: 'Gift of God' },
    { id: 4, name: 'Emma', description: 'Universal' },
    { id: 5, name: 'Gabriel', description: 'God is my strength' },
    { id: 6, name: 'Martina', description: 'Warlike' },
    { id: 7, name: 'Leo', description: 'Lion' },
    { id: 8, name: 'Giulia', description: 'Youthful' },
    { id: 9, name: 'Daniel', description: 'God is my judge' },
    { id: 10, name: 'Isabella', description: 'Devoted to God' },
    { id: 11, name: 'Andrea', description: 'Manly' },
    { id: 12, name: 'Valentina', description: 'Strong' },
    { id: 13, name: 'Marco', description: 'Warlike' },
    { id: 14, name: 'Camila', description: 'Helper to the priest' },
    { id: 15, name: 'Diego', description: 'Supplanter' },
    { id: 16, name: 'Alessia', description: 'Defender' },
    { id: 17, name: 'Carlos', description: 'Free man' },
    { id: 18, name: 'Elena', description: 'Bright, shining light' },
    { id: 19, name: 'Adrian', description: 'From Hadria' },
    { id: 20, name: 'Mia', description: 'Mine' },
    { id: 21, name: 'Nicolas', description: 'People of victory' },
    { id: 22, name: 'Ariana', description: 'Very holy' },
    { id: 23, name: 'Javier', description: 'New house' },
    { id: 24, name: 'Sara', description: 'Princess' },
    { id: 25, name: 'Pablo', description: 'Small' },
    { id: 26, name: 'Bianca', description: 'White, pure' },
    { id: 27, name: 'David', description: 'Beloved' },
    { id: 28, name: 'Paola', description: 'Small' },
    { id: 29, name: 'Enzo', description: 'Ruler of the estate' },
    { id: 30, name: 'Natalia', description: 'Born on Christmas' },
    { id: 31, name: 'Thiago', description: 'May God protect' },
    { id: 32, name: 'Victoria', description: 'Victory' },
    { id: 33, name: 'Juan', description: 'God is gracious' },
    { id: 34, name: 'Clara', description: 'Bright, clear' },
    { id: 35, name: 'Samuel', description: 'Heard by God' },
    { id: 36, name: 'Lucia', description: 'Light' },
    { id: 37, name: 'Miguel', description: 'Who is like God?' },
    { id: 38, name: 'Irene', description: 'Peace' },
    { id: 39, name: 'Antonio', description: 'Priceless' },
    { id: 40, name: 'Mariana', description: 'Grace' },
    { id: 41, name: 'Sebastian', description: 'Venerable' },
    { id: 42, name: 'Alicia', description: 'Noble' },
    { id: 43, name: 'Pedro', description: 'Rock' },
    { id: 44, name: 'Gabriela', description: 'God is my strength' },
    { id: 45, name: 'Jorge', description: 'Farmer' },
    { id: 46, name: 'Carolina', description: 'Free man' },
    { id: 47, name: 'Raul', description: 'Wolf counsel' },
    { id: 48, name: 'Laura', description: 'Laurel' },
    { id: 49, name: 'Mario', description: 'Mars' },
    { id: 50, name: 'Renata', description: 'Reborn' }
];
