const babyNames = [
    {
        "id": 1,
        "name": "Sofia",
        "description": "Wisdom",
        "tags": ["Female", "Greek", "Virtue"]
    },
    {
        "id": 2,
        "name": "Luca",
        "description": "Light",
        "tags": ["Male", "Italian", "Nature"]
    },
    {
        "id": 3,
        "name": "Mateo",
        "description": "Gift of God",
        "tags": ["Male", "Spanish", "Religious"]
    },
    {
        "id": 4,
        "name": "Emma",
        "description": "Universal",
        "tags": ["Female", "German", "Virtue"]
    },
    {
        "id": 5,
        "name": "Gabriel",
        "description": "God is my strength",
        "tags": ["Male", "Hebrew", "Religious"]
    },
    {
        "id": 6,
        "name": "Martina",
        "description": "Warlike",
        "tags": ["Female", "Latin", "Strong"]
    },
    {
        "id": 7,
        "name": "Leo",
        "description": "Lion",
        "tags": ["Male", "Latin", "Nature"]
    },
    {
        "id": 8,
        "name": "Giulia",
        "description": "Youthful",
        "tags": ["Female", "Italian", "Virtue"]
    },
    { id: 9, name: 'Daniel', description: 'God is my judge', tags: ['male', 'Hebrew', 'religious'] },
    { id: 10, name: 'Isabella', description: 'Devoted to God', tags: ['female', 'Hebrew', 'religious'] },
    { id: 11, name: 'Andrea', description: 'Manly', tags: ['male', 'Greek', 'virtue'] },
    { id: 12, name: 'Valentina', description: 'Strong', tags: ['female', 'Latin', 'virtue'] },
    { id: 13, name: 'Marco', description: 'Warlike', tags: ['male', 'Latin', 'warrior'] },
    { id: 14, name: 'Camila', description: 'Helper to the priest', tags: ['female', 'Latin', 'religious'] },
    { id: 15, name: 'Diego', description: 'Supplanter', tags: ['male', 'Spanish', 'biblical'] },
    { id: 16, name: 'Alessia', description: 'Defender', tags: ['female', 'Italian', 'virtue'] },
    { id: 17, name: 'Carlos', description: 'Free man', tags: ['male', 'Spanish', 'virtue'] },
    { id: 18, name: 'Elena', description: 'Bright, shining light', tags: ['female', 'Greek', 'virtue'] },
    { id: 19, name: 'Adrian', description: 'From Hadria', tags: ['male', 'Latin', 'place'] },
    { id: 20, name: 'Mia', description: 'Mine', tags: ['female', 'Latin', 'virtue'] },
    { id: 21, name: 'Nicolas', description: 'People of victory', tags: ['male', 'Greek', 'victory'] },
    { id: 22, name: 'Ariana', description: 'Very holy', tags: ['female', 'Hebrew', 'religious'] },
    { id: 23, name: 'Javier', description: 'New house', tags: ['male', 'Basque', 'place'] },
    { id: 24, name: 'Sara', description: 'Princess', tags: ['female', 'Hebrew', 'title'] },
    { id: 25, name: 'Pablo', description: 'Small', tags: ['male', 'Latin', 'virtue'] },
    { id: 26, name: 'Bianca', description: 'White, pure', tags: ['female', 'Italian', 'color'] },
    { id: 27, name: 'David', description: 'Beloved', tags: ['male', 'Hebrew', 'religious'] },
    { id: 28, name: 'Paola', description: 'Small', tags: ['female', 'Latin', 'virtue'] },
    { id: 29, name: 'Enzo', description: 'Ruler of the estate', tags: ['male', 'Italian', 'ruler'] },
    { id: 30, name: 'Natalia', description: 'Born on Christmas', tags: ['female', 'Latin', 'holiday'] },
    { id: 31, name: 'Thiago', description: 'May God protect', tags: ['male', 'Portuguese', 'religious'] },
    { id: 32, name: 'Victoria', description: 'Victory', tags: ['female', 'Latin', 'virtue'] },
    { id: 33, name: 'Juan', description: 'God is gracious', tags: ['male', 'Spanish', 'religious'] },
    { id: 34, name: 'Clara', description: 'Bright, clear', tags: ['female', 'Latin', 'virtue'] },
    { id: 35, name: 'Samuel', description: 'Heard by God', tags: ['male', 'Hebrew', 'religious'] },
    { id: 36, name: 'Lucia', description: 'Light', tags: ['female', 'Latin', 'virtue'] },
    { id: 37, name: 'Miguel', description: 'Who is like God?', tags: ['male', 'Hebrew', 'religious'] },
    { id: 38, name: 'Irene', description: 'Peace', tags: ['female', 'Greek', 'virtue'] },
    { id: 39, name: 'Antonio', description: 'Priceless', tags: ['male', 'Latin', 'virtue'] },
    { id: 40, name: 'Mariana', description: 'Grace', tags: ['female', 'Latin', 'virtue'] },
    { id: 41, name: 'Sebastian', description: 'Venerable', tags: ['male', 'Greek', 'virtue'] },
    { id: 42, name: 'Alicia', description: 'Noble', tags: ['female', 'Spanish', 'virtue'] },
    { id: 43, name: 'Pedro', description: 'Rock', tags: ['male', 'Spanish', 'religious'] },
    { id: 44, name: 'Gabriela', description: 'God is my strength', tags: ['female', 'Hebrew', 'religious'] },
    { id: 45, name: 'Jorge', description: 'Farmer', tags: ['male', 'Spanish', 'occupation'] },
    { id: 46, name: 'Carolina', description: 'Free man', tags: ['female', 'Spanish', 'virtue'] },
    { id: 47, name: 'Raul', description: 'Wolf counsel', tags: ['male', 'Spanish', 'animal'] },
    { id: 48, name: 'Laura', description: 'Laurel', tags: ['female', 'Latin', 'plant'] },
    { id: 49, name: 'Mario', description: 'Mars', tags: ['male', 'Latin', 'mythological'] },
    { id: 50, name: 'Renata', description: 'Reborn', tags: ['female', 'Latin', 'virtue'] },
    { id: 1, name: 'Alexandra', description: 'Defender of the people', tags: ['female', 'Greek', 'virtue'] },
    { id: 2, name: 'Ariadne', description: 'Very holy', tags: ['female', 'Greek', 'religious'] },
    { id: 3, name: 'Athena', description: 'Goddess of wisdom, war, and justice', tags: ['female', 'Greek', 'mythological'] },
    { id: 4, name: 'Cora', description: 'Maiden, young girl', tags: ['female', 'Greek', 'virtue'] },

  { id: 5, name: 'Daphne', description: 'Laurel', tags: ['female', 'Greek', 'plant'] },
    { id: 6, name: 'Eleni', description: 'Ray of sun', tags: ['female', 'Greek', 'natural'] },
    { id: 7, name: 'Galatea', description: 'White as milk', tags: ['female', 'Greek', 'color'] },
    { id: 8, name: 'Kleio', description: 'Glory', tags: ['female', 'Greek', 'virtue'] },
    { id: 9, name: 'Nikoleta', description: 'Victory of the people', tags: ['female', 'Greek', 'victory'] },
    { id: 10, name: 'Thalia', description: 'Flourishing, verdant', tags: ['female', 'Greek', 'nature'] },
    { id: 11, name: 'Aisha', description: 'Life, vivacious', tags: ['female', 'Arabic', 'virtue'] },
    { id: 12, name: 'Amira', description: 'Princess', tags: ['female', 'Arabic', 'title'] },
    { id: 13, name: 'Fatima', description: 'Daughter of the prophet', tags: ['female', 'Arabic', 'religious'] },
    { id: 14, name: 'Leila', description: 'Night', tags: ['female', 'Arabic', 'time'] },
    { id: 15, name: 'Maryam', description: 'Mary, mother of Jesus', tags: ['female', 'Arabic', 'religious'] },
    { id: 16, name: 'Nour', description: 'Light', tags: ['female', 'Arabic', 'virtue'] },
    { id: 17, name: 'Rania', description: 'Queen', tags: ['female', 'Arabic', 'title'] },
    { id: 18, name: 'Salma', description: 'Safe, peaceful', tags: ['female', 'Arabic', 'virtue'] },
    { id: 19, name: 'Yasmin', description: 'Jasmine', tags: ['female', 'Arabic', 'flower'] },
    { id: 20, name: 'Zainab', description: 'Fragrance', tags: ['female', 'Arabic', 'virtue'] },
    { id: 21, name: 'Aine', description: 'Brilliance, splendor', tags: ['female', 'Irish', 'virtue'] },
    { id: 22, name: 'Briana', description: 'Strong, high', tags: ['female', 'Irish', 'virtue'] },
    { id: 23, name: 'Brigid', description: 'Strength, exaltation', tags: ['female', 'Irish', 'virtue'] },
    { id: 24, name: 'Eilidh', description: 'Ray of sun', tags: ['female', 'Scottish', 'natural'] },
    { id: 25, name: 'Gwyneth', description: 'White, fortunate', tags: ['female', 'Welsh', 'color'] },
    { id: 26, name: 'Isolde', description: 'Ice fighter', tags: ['female', 'Welsh', 'virtue'] },
    { id: 27, name: 'Liriel', description: 'Daughter of the sea', tags: ['female', 'Welsh', 'nature'] },
    { id: 28, name: 'Maeve', description: 'Joyful', tags: ['female', 'Irish', 'virtue'] },
    { id: 29, name: 'Niamh', description: 'Radiant, shining', tags: ['female', 'Irish', 'virtue'] },
    { id: 30, name: 'Rhiannon', description: 'Great queen, divinity', tags: ['female', 'Welsh', 'title'] },
    { id: 31, name: 'Ailani', description: 'High nobility, princess', tags: ['female', 'Hawaiian', 'title'] },
    { id: 32, name: 'Halia', description: 'Remember', tags: ['female', 'Hawaiian', 'virtue'] },
    { id: 33, name: 'Kailani', description: 'Sea and sky', tags: ['female', 'Hawaiian', 'nature'] },
    { id: 34, name: 'Kalea', description: 'Brightness, joy', tags: ['female', 'Hawaiian', 'virtue'] },
    { id: 35, name: 'Leilani', description: 'Royal flower', tags: ['female', 'Hawaiian', 'flower'] },
    { id: 36, name: 'Mahina', description: 'Moon', tags: ['female', 'Hawaiian', 'nature'] },
    { id: 37, name: 'Malia', description: 'Calm, tranquil', tags: ['female', 'Hawaiian', 'virtue'] },
    { id: 38, name: 'Nalani', description: 'Serene sky', tags: ['female', 'Hawaiian', 'nature'] },
    { id: 39, name: 'Pua', description: 'Flower', tags: ['female', 'Hawaiian', 'flower'] },
    { id: 40, name: 'Wailani', description: 'Watery sky', tags: ['female', 'Hawaiian', 'nature'] },
    { id: 41, name: 'Alika', description: 'The most beautiful', tags: ['female', 'Hawaiian', 'virtue'] },
    { id: 42, name: 'Ife', description: 'Love', tags: ['female', 'Yoruba', 'virtue'] },
    { id: 43, name: 'Johari', description: 'Gem, jewel', tags: ['female', 'Swahili', 'precious'] },
    { id: 44, name: 'Kenia', description: 'One who comes from the luminous mountain', tags: ['female', 'Swahili', 'place'] },
    { id: 45, name: 'Nadjela', description: 'Beautiful gaze', tags: ['female', 'Serbo-Croatian', 'beauty'] },
    { id: 46, name: 'Naina', description: 'Beautiful eyes', tags: ['female', 'Indian', 'beauty'] },
    { id: 47, name: 'Nia', description: 'Purpose, intention', tags: ['female', 'Welsh', 'virtue'] },
    { id: 48, name: 'Safiya', description: 'Pure, sincere', tags: ['female', 'Arabic', 'virtue'] },
    { id: 49, name: 'Sanza', description: 'Beautiful melody', tags: ['female', 'African', 'beauty'] },
    { id: 50, name: 'Tariro', description: 'Hope', tags: ['female', 'Shona', 'virtue'] },
    { id: 51, name: 'Amara', description: 'Eternal', tags: ['female', 'Latin', 'virtue'] },
    { id: 52, name: 'Anaya', description: 'Caring', tags: ['female', 'Hebrew', 'virtue'] },
    { id: 53, name: 'Elara', description: 'Bright, shining', tags: ['female', 'Greek', 'virtue'] },
    { id: 54, name: 'Mira', description: 'Ocean', tags: ['female', 'Latin', 'nature'] },
    { id: 55, name: 'Nadia', description: 'Hope', tags: ['female', 'Slavic', 'virtue'] },

    { "id": 56, "name": "Seraphina", "description": "Fiery" },
    { "id": 57, "name": "Zara", "description": "Princess" },
    { "id": 58, "name": "Alina", "description": "Bright, beautiful" },
    { "id": 59, "name": "Diana", "description": "Divine" },
    { "id": 60, "name": "Jasmine", "description": "Flower" },
    { "id": 61, "name": "Luna", "description": "Moon" },
    { "id": 62, "name": "Aurelia", "description": "Golden" },
    { "id": 63, "name": "Isla", "description": "Island" },
    { "id": 64, "name": "Ivy", "description": "Faithfulness" },
    { "id": 65, "name": "Lyra", "description": "Lyre" },
    { "id": 66, "name": "Ophelia", "description": "Help" },
    { "id": 67, "name": "Rosa", "description": "Rose" },
    { "id": 68, "name": "Aurora", "description": "Dawn" },
    { "id": 69, "name": "Elena", "description": "Bright, shining light" },
    { "id": 70, "name": "Clara", "description": "Clear, bright" },
    { "id": 71, "name": "Celeste", "description": "Heavenly" },
    { "id": 72, "name": "Freya", "description": "Noble woman" },
    { "id": 73, "name": "Nora", "description": "Honor" },
    { "id": 74, "name": "Violet", "description": "Flower" },
    { "id": 75, "name": "Zoe", "description": "Life" },
    { "id": 76, "name": "Evelyn", "description": "Wished for child" },
    { "id": 77, "name": "Hannah", "description": "Grace" },
    { "id": 78, "name": "Maya", "description": "Illusion" },
    { "id": 79, "name": "Naomi", "description": "Pleasantness" },
    { "id": 80, "name": "Sophie", "description": "Wisdom" },
    { "id": 81, "name": "Aria", "description": "Air, melody" },
    { "id": 82, "name": "Elsa", "description": "Noble" },
    { "id": 83, "name": "Beatrice", "description": "Bringer of happiness" },
    { "id": 84, "name": "Juliet", "description": "Youthful" },
    { "id": 85, "name": "Anastasia", "description": "Resurrection" },
    { "id": 86, "name": "Bella", "description": "Beautiful" },
    { "id": 87, "name": "Giselle", "description": "Pledge" },
    { "id": 88, "name": "Margo", "description": "Pearl" },
    { "id": 89, "name": "Vivian", "description": "Life" },
    { "id": 90, "name": "Mila", "description": "Gracious" },
    { "id": 91, "name": "Amelia", "description": "Work" },
    { "id": 92, "name": "Lydia", "description": "Noble" },
    { "id": 93, "name": "Sienna", "description": "Orange-red" },
    { "id": 94, "name": "Athena", "description": "Wisdom" },
    { "id": 95, "name": "Selena", "description": "Moon" },
    { "id": 96, "name": "Juno", "description": "Queen of the heavens" },
    { "id": 97, "name": "Fiona", "description": "Fair" },
    { "id": 98, "name": "Margaret", "description": "Pearl" },
    { "id": 99, "name": "Riley", "description": "Valiant" },
    { "id": 100, "name": "Georgia", "description": "Farmer" },
    { "id": 101, "name": "Hazel", "description": "The hazel tree" },
    { "id": 102, "name": "Lila", "description": "Night" },
    { "id": 103, "name": "Cora", "description": "Maiden" },
    { "id": 104, "name": "Ruby", "description": "Red gemstone" },
    { "id": 105, "name": "Daisy", "description": "Day's eye" },
    { "id": 106, "name": "Rosa", "description": "Rose" },
    { "id": 107, "name": "Holly", "description": "Holly tree" },
    { "id": 108, "name": "Iris", "description": "Rainbow" },
    { "id": 109, "name": "Penelope", "description": "Weaver" },
    { "id": 110, "name": "Alice", "description": "Noble" },
    { "id": 111, "name": "Diana", "description": "Divine" },
    { "id": 112, "name": "Esther", "description": "Star" },
    { "id": 113, "name": "Felicity", "description": "Happiness" },
    { "id": 114, "name": "Gwendolyn", "description": "Blessed ring" },
    { "id": 115, "name": "Ivy", "description": "Faithfulness" },
    { "id": 116, "name": "Ruth", "description": "Friend" },
    { "id": 117, "name": "Vivian", "description": "Alive" },
    { "id": 118, "name": "Eleanor", "description": "Shining light" },
    { "id": 119, "name": "Grace", "description": "Grace" },
    { "id": 120, "name": "Helen", "description": "Light" },
    { "id": 121, "name": "Jane", "description": "God is gracious" },
    { "id": 122, "name": "June", "description": "Born in June" },
    { "id": 123, "name": "Lila", "description": "Night" },
    { "id": 124, "name": "Nina", "description": "Little girl" },
    { "id": 125, "name": "Piper", "description": "Pipe player" },
    { "id": 126, "name": "Samantha", "description": "Listener" },
    { "id": 127, "name": "Sydney", "description": "Wide meadow" },
    { "id": 128, "name": "Tessa", "description": "Harvester" },
    { "id": 129, "name": "Zara", "description": "Princess" },
    { "id": 130, "name": "Adeline", "description": "Noble" },
    { "id": 131, "name": "Celeste", "description": "Heavenly" },
    { "id": 132, "name": "Daphne", "description": "Laurel" },
    { "id": 133, "name": "Elena", "description": "Shining light" },
    { "id": 134, "name": "Gia", "description": "God's gracious gift" },
    { "id": 135, "name": "Hazel", "description": "The hazel tree" },
  { "name": "AINGERU", "description": "Basque form of Latin Angelus, meaning 'angel, messenger.'" },
    { "name": "AITOR", "description": "'Good father.' In the 19th century, French Basque author Augustin Chaho published The Legend of Aitor, based on a belief of the Basque people that they are aitoren semeak, 'sons of the good father,' a descendant of biblical Tubal." },
    { "name": "ALESANDER", "description": "Basque form of Alexander, meaning 'defender of mankind.'" },
    { "name": "AMETS", "description": "Basque unisex name meaning 'dream.'" },
    { "name": "ANAIA", "description": "Basque name meaning 'brother.'" },
    { "name": "ANAUT", "description": "Basque form of Arnold, meaning 'eagle power.'" },
    { "name": "ANDER", "description": "Basque form of Andrew, meaning 'man; warrior.'" },
    { "name": "ANDONI", "description": "Basque form of Roman Antonius, possibly meaning 'invaluable.'" },
    { "name": "ANTTON", "description": "Basque form of Roman Antonius, possibly meaning 'invaluable.'" },
    { "name": "ABARRAN", "description": "Basque form of Abraham, meaning 'father of a multitude.'" },
    { "name": "APAL", "description": "Basque name meaning 'humble.'" },
    { "name": "ARESTI", "description": "Basque name meaning 'instant.'" },
    { "name": "ARGI", "description": "Basque name meaning 'light.'" },
    { "name": "ARGIDER", "description": "'Light of beauty.' Basque name derived from the elements argi 'light' and eder 'beautiful.'" },
    { "name": "ARNAS", "description": "Basque name meaning 'breath.'" },
    { "name": "AROTZA", "description": "Basque name meaning 'carpenter.'" },
    { "name": "ARRATS", "description": "Basque unisex name meaning 'early evening; dusk.'" },
    { "name": "ARTIZAR", "description": "Unisex name meaning 'morning star; Venus.'" },
    { "name": "ARTZAI", "description": "Basque name meaning 'shepherd.'" },
    { "name": "ASENTZIO", "description": "Basque name meaning 'ascension.'" },
    { "name": "ASTIGAR", "description": "Basque name meaning 'maple.'" },
    { "name": "ATSEDEN", "description": "Basque name meaning 'rest.'" },
    { "name": "ATZE", "description": "Basque name meaning 'behind.'" },
    { "name": "ATZO", "description": "Basque name meaning 'yesterday.'" },
    { "name": "BAKAR", "description": "Basque name meaning 'alone.'" },
    { "name": "BALENDIN", "description": "Basque form of Latin Valentinus, meaning 'healthy, strong.'" },
    { "name": "BAREA", "description": "Basque name meaning 'clam.'" },
    { "name": "BASAJAUN", "description": "Basque folklore name, meaning 'lord of the woods,' from baso 'woods' and jaun 'lord.'" },
    { "name": "BELASKO", "description": "Basque name meaning 'raven.'" },
    { "name": "BENAT (Beñat)", "description": "Basque form of Bernard, meaning 'bold as a bear.'" },
    { "name": "BELTZA", "description": "Basque name meaning 'black.'" },
    { "name": "BENAT", "description": "Basque form of Bernard, meaning 'bold as a bear.'" },
    { "name": "BERBIZ", "description": "Basque name meaning 'resurrection.'" },
    { "name": "BERNAT", "description": "Basque form of Bernard, meaning 'bold as a bear.'" },
    { "name": "BERO", "description": "Basque name meaning 'hot.'" },
    { "name": "BETI", "description": "Basque form of Peter, meaning 'rock; stone.'" },
    { "name": "BIHAR", "description": "Basque name meaning 'tomorrow.'" },
    { "name": "BIKENDI", "description": "Basque form of English Vincent, meaning 'conquering.'" },
    { "name": "BINGEN", "description": "Basque form of Vincent, meaning 'conquering.'" },
    { "name": "BITTOR", "description": "Basque form of Roman Victor, meaning 'to conquer; victory.'" },
    { "name": "BIXINTXO", "description": "Basque form of Vincent, meaning 'conquering.'" },
    { "name": "BOLIVAR", "description": "'Meadow/riverbank mill.' Castilian name derived from the Basque place name Bolibar, itself from Basque bolu 'mill' and ibar 'meadow, riverbank.'" },
    { "name": "DANEL", "description": "Basque form of Daniel, meaning 'God is my judge.'" },
    { "name": "DEUNORO", "description": "Basque name meaning 'all saints.'" },
    { "name": "DOMEKA", "description": "Basque form of Dominic, meaning 'belongs to the lord.'" },
    { "name": "DUNIXI", "description": "Basque form of Latin Dionysius, meaning 'follower of Dionysos.'" },
    { "name": "EDER", "description": "Basque unisex name meaning 'beautiful, handsome.'" },
    { "name": "EDORTA", "description": "Basque form of English Edward, meaning 'guardian of prosperity.'" },
    { "name": "EDUR", "description": "Basque name meaning 'snow.'" },
    { "name": "EGUN", "description": "Basque name meaning 'day.'" },
    { "name": "EGUNTSENTI", "description": "Basque name meaning 'dawn.'" },
    { "name": "EGUZKI", "description": "Basque name meaning 'sun.'" },
    { "name": "EKAIN", "description": "Basque month name meaning 'June.'" },
    { "name": "EKAITZ", "description": "Basque name meaning 'storm.'" },
    { "name": "EKIALDE", "description": "Basque name meaning 'east.'" },
    { "name": "ELAZAR", "description": "Basque form of Eleazar, meaning 'my god has helped.'" },
    { "name": "ELEDER", "description": "Basque name meaning 'eloquent.'" },
    { "name": "ELI", "description": "Basque form of Elias, meaning 'the Lord is my God.'" },
    { "name": "ELORRI", "description": "Basque name meaning 'thorn.'" },
    { "name": "ENDIKA", "description": "Basque form of Henry, meaning 'home-ruler.'" },
    { "name": "ENEKO", "description": "Old Basque name meaning 'place in the slope of a mountain.'" },
    { "name": "ERLANTZ", "description": "Basque form of Visigothic Ferdinand, meaning 'journey-prepared.'" },
    { "name": "ERLEA", "description": "Basque unisex name meaning 'bee.'" },
    { "name": "ERRAMUN", "description": "Basque form of English Raymond, meaning 'wise protector.'" },
    { "name": "ERRAPEL", "description": "Basque form of Raphael, meaning 'God has healed.'" },
    { "name": "ERRUKI", "description": "Basque name meaning 'pious.'" },
    { "name": "ESKUIN", "description": "Basque name meaning 'right.'" },
    { "name": "ESTEBE", "description": "Basque form of Greek Stephanos, meaning 'crown.'" },
    { "name": "EZTEBE", "description": "Basque form of English Stephen, meaning 'crown.'" },
    { "name": "FRANTZES", "description": "Basque form of Francis, meaning 'free.'" },
    { "name": "FRANTZISKO", "description": "Basque form of Latin Franciscus, meaning 'free.'" },
    { "name": "GABIREL", "description": "Basque form of Gabriel, meaning 'strong man of God.'" },
    { "name": "GAIZKA", "description": "Basque name meaning 'savior.'" },
    { "name": "GANIX", "description": "Basque form of John, meaning 'God is gracious.'" },
    { "name": "GARAILE", "description": "Basque name meaning 'champion, victor.'" },
    { "name": "GAROA", "description": "Basque name meaning 'fern.'" },
      { "name": "GARTZI", "description": "Basque name meaning 'grace.'" },
    { "name": "GAU", "description": "Basque name meaning 'night.'" },
    { "name": "GAZTEA", "description": "Basque name meaning 'youth.'" },
    { "name": "GENTZA", "description": "Basque name meaning 'peace.'" },
    { "name": "GERGORI", "description": "Basque form of Gregory, meaning 'watchful; vigilant.'" },
    { "name": "GERO", "description": "Basque name meaning 'future.'" },
    { "name": "GILEN", "description": "Basque form of William, meaning 'will-helmet.'" },
    { "name": "GIRO", "description": "Basque name meaning 'weather.'" },
    { "name": "GIZON", "description": "Basque name meaning 'man.'" },
    { "name": "GOGO", "description": "Basque name meaning 'spirit.'" },
    { "name": "GOIZ", "description": "Basque name derived from the element goiz, meaning 'morning.'" },
    { "name": "GORA", "description": "Basque name meaning 'exaltation.'" },
    { "name": "GORKA", "description": "Basque form of Greek Georgios, meaning 'earth-worker, farmer.'" },
    { "name": "GORRI", "description": "Basque name meaning 'red.'" },
    { "name": "GOTZON", "description": "Basque name meaning 'angel.'" },
    { "name": "GURUTZ", "description": "Basque name meaning 'cross.'" },
    { "name": "GUTXI", "description": "Basque name meaning 'little.'" },
    { "name": "HARITZ", "description": "Basque name meaning 'oak.'" },
    { "name": "HARKAITZ", "description": "Basque name meaning 'rock.'" },
    { "name": "HARTZ", "description": "Basque name meaning 'bear.'" },
    { "name": "HATS", "description": "Basque name meaning 'breath.'" },
    { "name": "HERENSUGE", "description": "Basque legend name of a dragon, meaning 'dragon.'" },
    { "name": "HIBAI", "description": "Basque name meaning 'river.'" },
    { "name": "HODEI", "description": "Basque name meaning 'cloud.'" },
    { "name": "HORI", "description": "Basque name meaning 'yellow.'" },
    { "name": "IBAR", "description": "Basque name meaning 'valley.'" },
    { "name": "IGON", "description": "Basque name meaning 'ascension.'" },
    { "name": "IHINTZA", "description": "Basque unisex name meaning 'dew.'" },
    { "name": "IKATZ", "description": "Basque name meaning 'coal.'" },
    { "name": "IMANOL", "description": "Basque form of biblical Emmanuel, meaning 'God is with us.'" },
    { "name": "INAKI", "description": "Basque form of Latin Ignatius, possibly meaning 'unknowing.'" },
    { "name": "INDAR", "description": "Basque name meaning 'strength.'" },
    { "name": "INEKO", "description": "Probably a Basque form of Latin Ignatius, possibly meaning 'unknowing.'" },
    { "name": "ION", "description": "Basque and Romanian form of John, meaning 'God is gracious.'" },
    { "name": "IPAR", "description": "Basque name meaning 'north.'" },
    { "name": "ITURRI", "description": "Basque name meaning 'fountain.'" },
    { "name": "ITZAINA", "description": "Basque name meaning 'shepherd.'" },
    { "name": "ITZAL", "description": "Basque name meaning 'shadow.'" },
    { "name": "IXAKA", "description": "Basque form of Isaac, meaning 'he will laugh.'" },
    { "name": "IXIDOR", "description": "Basque form of Isidor, meaning 'gift of Isis.'" },
    { "name": "IZOTZ", "description": "Basque name meaning 'ice.'" },
    { "name": "JAKES", "description": "Basque form of Jacob, meaning 'supplanter.'" },
    { "name": "JOANES", "description": "Basque form of English John, meaning 'God is gracious.'" },
    { "name": "JOKIN", "description": "Basque form of Joachim, meaning 'established by God.'" },
    { "name": "JON", "description": "Basque and Scandinavian form of English John, meaning 'God is gracious.'" },
    { "name": "JOSEBA", "description": "Basque form of Joseph, meaning '(God) shall add,' which is usually taken to mean 'God will add another son.'" },
    { "name": "JOSEPE", "description": "Basque form of Joseph, meaning '(God) shall add,' which is usually taken to mean 'God will add another son.'" },
    { "name": "JOSU", "description": "Basque form of Jesus, meaning 'Yahweh is salvation.'" },
    { "name": "JULEN", "description": "Basque form of Roman Julianus, possibly meaning 'soft-bearded.'" },
    { "name": "KEMEN", "description": "Basque name meaning 'courage, vigor.'" },
    { "name": "KEPA", "description": "Basque form of Aramaic Cephas, meaning 'rock.'" },
    { "name": "KERMAN", "description": "Basque form of Roman Germanus, meaning 'brother.'" },
    { "name": "KIMETZ", "description": "Basque name meaning 'sprout.'" },
    { "name": "KERBASI", "description": "Basque name meaning 'warrior.'" },
    { "name": "KOLDO", "description": "Nickname for Basque Koldobika, meaning 'famous warrior.'" },
    { "name": "KOLDOBIKA", "description": "Basque form of French Louis, meaning 'famous warrior.'" },
    { "name": "LAURENDI", "description": "Basque form of Laurence, meaning 'of Laurentum.'" },
    { "name": "LAURENTZI", "description": "Basque form of Laurence, meaning 'of Laurentum.'" },
    { "name": "LEHOI", "description": "Basque name meaning 'lion.'" },
    { "name": "LER", "description": "Basque name meaning 'pine.'" },
    { "name": "LERTXUN", "description": "Basque name meaning 'aspen.'" },
    { "name": "LIHER", "description": "Masculine form of Basque Liernia, the patron saint of mothers without milk or who are unable to conceive." },
    { "name": "LIZAR", "description": "Basque name meaning 'ash.'" },
    { "name": "LIZARDI", "description": "Basque name meaning 'ash tree grove.'" },
    { "name": "LON", "description": "Basque form of Leon, meaning 'lion.'" },
    { "name": "LORE", "description": "Basque unisex name meaning 'flower.'" },
    { "name": "LUIX", "description": "Basque form of Luis, meaning 'famous warrior.'" },
    { "name": "LUKEN", "description": "Basque form of Roman Lucianus, meaning 'light.'" },
    { "name": "LUZEA", "description": "Basque name meaning 'long.'" },
    { "name": "MARKEL", "description": "Basque form of Roman Martialis, meaning 'of Mars.'" },
    { "name": "MARKO", "description": "Basque, Bulgarian, and Ukrainian form of Latin Mark, meaning 'warlike.'" },
    { "name": "MARTZEL", "description": "Basque form of Roman Marcellus, meaning 'warlike.'" },
    { "name": "MARZ", "description": "Basque form of Latin Mark, meaning 'warlike.'" },
    { "name": "MATIA", "description": "Basque form of Matthew, meaning 'gift of God.'" },
    { "name": "MATTIN", "description": "Basque form of Latin Martinus, meaning 'of/like Mars.'" },
    { "name": "MATXIN", "description": "Basque form of Latin Martinus, meaning 'of/like Mars.'" },
    { "name": "MENDEBAL", "description": "Basque name meaning 'west.'" },
    { "name": "MIKEL", "description": "Basque form of Michael, meaning 'who is like God?'" },
    { "name": "MITXEL", "description": "Basque form of Michael, meaning 'who is like God?'" },
    { "name": "NIKOLA", "description": "Basque, Bulgarian, and Hungarian form of Nicholas, meaning 'victory of the people.'" },
    { "name": "ODOL", "description": "Basque name meaning 'blood.'" },
    { "name": "ORKATZ", "description": "Basque name meaning 'deer.'" },
    { "name": "OROITZ", "description": "Basque name meaning 'memory.'" },
    { "name": "ORTLE", "description": "Basque name meaning 'firmament.'" },
    { "name": "ORTZI", "description": "Basque name meaning 'sky.'" },
    { "name": "OSKARBI", "description": "Basque name meaning 'clear sky.'" },
    { "name": "OSTADAR", "description": "Basque name meaning 'rainbow.'" },
    { "name": "OSTARGI", "description": "Basque name meaning 'aurora.'" },
    { "name": "OSTOTS", "description": "Basque name meaning 'thunder.'" },
    { "name": "OTSOA", "description": "Basque name meaning 'wolf.'" },
    { "name": "OTSOKO", "description": "Basque name meaning 'wolf cub.'" },
    { "name": "PANTZESKA", "description": "Basque form of Latin Franciscus, meaning 'free.'" },
    { "name": "PATXI", "description": "Pet form of Basque Pantzeska, meaning 'free.'" },
    { "name": "PAULIN", "description": "Basque form of Paul, meaning 'small.'" },
    { "name": "PAULO", "description": "Basque form of Paul, meaning 'small.'" },
    { "name": "PEIO", "description": "Basque form of Peter, meaning 'rock; stone.'" },
    { "name": "PELI", "description": "Basque form of Felix, meaning 'lucky.'" },
    { "name": "PERU", "description": "Basque form of Peter, meaning 'rock; stone.'" },
    { "name": "PETRI", "description": "Basque form of Peter, meaning 'rock; stone.'" },
    { "name": "SALBATORE", "description": "Basque name meaning 'savior.'" },
    { "name": "SANTUTXO", "description": "Basque name meaning 'little saint.'" },
    { "name": "SEME", "description": "Basque name meaning 'son.'" },
    { "name": "SENDOA", "description": "Basque name meaning 'strong.'" },
    { "name": "SU", "description": "Basque name meaning 'fire.'" },
    { "name": "TEOBALDO", "description": "Basque form of Theobald, meaning 'people-bold.'" },
    { "name": "TIBALT", "description": "Basque form of Theobald, meaning 'people-bold.'" },
    { "name": "TIPI", "description": "Basque name meaning 'small.'" },
    { "name": "TODOR", "description": "Basque form of Theodore, meaning 'gift of God.'" },
    { "name": "TUBAL", "description": "Biblical name of a son of Japheth, and possibly the ancestor of the Basques (see Aitor)." },
    { "name": "TXATXU", "description": "Basque name meaning 'foolish.'" },
    { "name": "TXERU", "description": "Basque name meaning 'sky.'" },
    { "name": "TXILAR", "description": "Basque name meaning 'heather.'" },
    { "name": "TXOMIN", "description": "Basque form of English Dominic, meaning 'belongs to the lord.'" },
    { "name": "UHIN", "description": "Basque name meaning 'ocean wave.'" },
    { "name": "UMEA", "description": "Basque name meaning 'child.'" },
    { "name": "UNAI", "description": "Basque name meaning 'shepherd.'" },
    { "name": "UR", "description": "Basque name meaning 'water.'" },
    { "name": "URDIN", "description": "Basque name meaning 'blue.'" },
    { "name": "URKI", "description": "Basque name meaning 'birch tree.'" },
    { "name": "URRE", "description": "Basque name meaning 'gold.'" },
    { "name": "XABIER", "description": "Basque and Galician form of English Xavier, meaning 'a new house.'" },
    { "name": "XALBADOR", "description": "Basque name meaning 'savior.'" },
    { "name": "XANTI", "description": "Basque form of Spanish Santiago, meaning 'Saint Iago.'" },
    { "name": "XARLES", "description": "Basque form of Charles, meaning 'man.'" },
    { "name": "XIMON", "description": "Variant of Basque Ximun, meaning 'hearkening.'" },
    { "name": "XIMUN", "description": "Basque form of Greek Simon, meaning 'hearkening.'" },
    { "name": "YULI", "description": "Basque name meaning 'youthful.'" },
    { "name": "ZERU", "description": "Basque name meaning 'sky.'" },
    { "name": "ZIGOR", "description": "Basque name meaning 'punishment.'" },
    { "name": "ZILAR", "description": "Basque name meaning 'silver.'" },
    { "name": "ZORION", "description": "Basque unisex name meaning 'happiness.'" },
    { "name": "ZUHAITZ", "description": "Basque unisex name meaning 'tree.'" },
    { "name": "ZUMAR", "description": "Basque name meaning 'elm.'" },
    { "name": "ZURI", "description": "Basque name meaning 'white.'" },
    { "name": "ZUZEN", "description": "Basque name meaning 'fair, just.'" }
];
