var d = [
AINGERU, name: ' Basque form of Latin Angelus, meaning "angel, messenger."
AITOR, name: ' "Good father." In the 19th century, French Basque author Augustin Chaho published The Legend of Aitor, based on a belief of the Basque people that they are aitoren semeak, "sons of the good father," a descendant of biblical Tubal.
ALESANDER, name: ' Basque form of Alexander, meaning "defender of mankind."
AMETS, name: ' Basque unisex name meaning "dream."
ANAIA, name: ' Basque name meaning "brother."
ANAUT, name: ' Basque form of Arnold, meaning "eagle power."
ANDER, name: ' Basque form of Andrew, meaning "man; warrior."
ANDONI, name: ' Basque form of Roman Antonius, possibly meaning "invaluable."
ANTTON, name: ' Basque form of Roman Antonius, possibly meaning "invaluable."
ABARRAN, name: ' Basque form of Abraham, meaning "father of a multitude."
APAL, name: ' Basque name meaning "humble."
ARESTI, name: ' Basque name meaning "instant."
ARGI, name: ' Basque name meaning "light."
ARGIDER, name: ' "Light of beauty." Basque name derived from the elements argi "light" and eder "beautiful."
ARNAS, name: ' Basque name meaning "breath."
AROTZA, name: ' Basque name meaning "carpenter."
ARRATS, name: ' Basque unisex name meaning "early evening; dusk."
ARTIZAR, name: ' Unisex name meaning "morning star; Venus."
ARTZAI, name: ' Basque name meaning "shepherd."
ASENTZIO, name: ' Basque name meaning "ascension."
ASTIGAR, name: ' Basque name meaning "maple."
ATSEDEN, name: ' Basque name meaning "rest."
ATZE, name: ' Basque name meaning "behind."
ATZO, name: ' Basque name meaning "yesterday."
BAKAR, name: ' Basque name meaning "alone."
BALENDIN, name: ' Basque form of Latin Valentinus, meaning "healthy, strong."
BAREA, name: ' Basque name meaning "clam."
BASAJAUN, name: ' Basque folklore name, meaning "lord of the woods," from baso "woods" and jaun "lord."
BELASKO, name: ' Basque name meaning "raven."
BENAT (Beñat), name: ' Basque form of Bernard, meaning "bold as a bear."
BELTZA, name: ' Basque name meaning "black."
BENAT, name: ' Basque form of Bernard, meaning "bold as a bear."
BERBIZ, name: ' Basque name meaning "resurrection."
BERNAT, name: ' Basque form of Bernard, meaning "bold as a bear."
BERO, name: ' Basque name meaning "hot."
BETI, name: ' Basque form of Peter, meaning "rock; stone."
BIHAR, name: ' Basque name meaning "tomorrow."
BIKENDI, name: ' Basque form of English Vincent, meaning "conquering."
BINGEN, name: ' Basque form of Vincent, meaning "conquering."
BITTOR, name: ' Basque form of Roman Victor, meaning "to conquer; victory."
BIXINTXO, name: ' Basque form of Vincent, meaning "conquering."
BOLIVAR, name: ' "Meadow/riverbank mill." Castilian name derived from the Basque place name Bolibar, itself from Basque bolu "mill" and ibar "meadow, riverbank."
DANEL, name: ' Basque form of Daniel, meaning "God is my judge."
DEUNORO, name: ' Basque name meaning "all saints."
DOMEKA, name: ' Basque form of Dominic, meaning "belongs to the lord."
DUNIXI, name: ' Basque form of Latin Dionysius, meaning "follower of Dionysos."
EDER, name: ' Basque unisex name meaning "beautiful, handsome."
EDORTA, name: ' Basque form of English Edward, meaning "guardian of prosperity."
EDUR, name: ' Basque name meaning "snow."
EGUN, name: ' Basque name meaning "day."
EGUNTSENTI, name: ' Basque name meaning "dawn."
EGUZKI, name: ' Basque name meaning "sun."
EKAIN, name: ' Basque month name meaning "June."
EKAITZ, name: ' Basque name meaning "storm."
EKIALDE, name: ' Basque name meaning "east."
ELAZAR, name: ' Basque form of Eleazar, meaning "my god has helped."
ELEDER, name: ' Basque name meaning "eloquent."
ELI, name: ' Basque form of Elias, meaning "the Lord is my God."
ELORRI, name: ' Basque name meaning "thorn."
ENDIKA, name: ' Basque form of Henry, meaning "home-ruler."
ENEKO, name: ' Old Basque name meaning "place in the slope of a mountain."
ERLANTZ, name: ' Basque form of Visigothic Ferdinand, meaning "journey-prepared."
ERLEA, name: ' Basque unisex name meaning "bee."
ERRAMUN, name: ' Basque form of English Raymond, meaning "wise protector."
ERRAPEL, name: ' Basque form of Raphael, meaning "God has healed."
ERRUKI, name: ' Basque name meaning "pious."
ESKUIN, name: ' Basque name meaning "right."
ESTEBE, name: ' Basque form of Greek Stephanos, meaning "crown."
EZTEBE, name: ' Basque form of English Stephen, meaning "crown."
FRANTZES, name: ' Basque form of Francis, meaning "free."
FRANTZISKO, name: ' Basque form of Latin Franciscus, meaning "free."
GABIREL, name: ' Basque form of Gabriel, meaning "strong man of God."
GAIZKA, name: ' Basque name meaning "savior."
GANIX, name: ' Basque form of John, meaning "God is gracious."
GARAILE, name: ' Basque name meaning "champion, victor."
GAROA, name: ' Basque name meaning "fern."
GARTZI, name: ' Basque name meaning "grace."
GAU, name: ' Basque name meaning "night."
GAZTEA, name: ' Basque name meaning "youth."
GENTZA, name: ' Basque name meaning "peace."
GERGORI, name: ' Basque form of Gregory, meaning "watchful; vigilant."
GERO, name: ' Basque name meaning "future."
GILEN, name: ' Basque form of William, meaning "will-helmet."
GIRO, name: ' Basque name meaning "weather."
GIZON, name: ' Basque name meaning "man."
GOGO, name: ' Basque name meaning "spirit."
GOIZ, name: ' Basque name derived from the element goiz, meaning "morning."
GORA, name: ' Basque name meaning "exaltation."
GORKA, name: ' Basque form of Greek Georgios, meaning "earth-worker, farmer."
GORRI, name: ' Basque name meaning "red."
GOTZON, name: ' Basque name meaning "angel."
GURUTZ, name: ' Basque name meaning "cross."
GUTXI, name: ' Basque name meaning "little."
HARITZ, name: ' Basque name meaning "oak."
HARKAITZ, name: ' Basque name meaning "rock."
HARTZ, name: ' Basque name meaning "bear."
HATS, name: ' Basque name meaning "breath."
HERENSUGE, name: ' Basque legend name of a dragon, meaning "dragon."
HIBAI, name: ' Basque name meaning "river."
HODEI, name: ' Basque name meaning "cloud."
HORI, name: ' Basque name meaning "yellow."
IBAR, name: ' Basque name meaning "valley."
IGON, name: ' Basque name meaning "ascension."
IHINTZA, name: ' Basque unisex name meaning "dew."
IKATZ, name: ' Basque name meaning "coal."
IMANOL, name: ' Basque form of biblical Emmanuel, meaning "God is with us."
INAKI (Iñaki), name: ' Basque form of Latin Ignatius, possibly meaning "unknowing."
INDAR, name: ' Basque name meaning "strength."
INEKO, name: ' Probably a Basque form of Latin Ignatius, possibly meaning "unknowing."
ION, name: ' Basque and Romanian form of John, meaning "God is gracious."
IPAR, name: ' Basque name meaning "north."
ITURRI, name: ' Basque name meaning "fountain."
ITZAINA, name: ' Basque name meaning "shepherd."
ITZAL, name: ' Basque name meaning "shadow."
IXAKA, name: ' Basque form of Isaac, meaning "he will laugh."
IXIDOR, name: ' Basque form of Isidor, meaning "gift of Isis."
IZOTZ, name: ' Basque name meaning "ice."
JAKES, name: ' Basque form of Jacob, meaning "supplanter."
JOANES, name: ' Basque form of English John, meaning "God is gracious."
JOKIN, name: ' Basque form of Joachim, meaning "established by God."
JON, name: ' Basque and Scandinavian form of English John, meaning "God is gracious."
JOSEBA, name: ' Basque form of Joseph, meaning "(God) shall add," which is usually taken to mean "God will add another son."
JOSEPE, name: ' Basque form of Joseph, meaning "(God) shall add," which is usually taken to mean "God will add another son."
JOSU, name: ' Basque form of Jesus, meaning "Yahweh is salvation."
JULEN, name: ' Basque form of Roman Julianus, possibly meaning "soft-bearded," a symbo
KEMEN, name: ' Basque name meaning "courage, vigor."
KEPA, name: ' Basque form of Aramaic Cephas, meaning "rock."
KERMAN, name: ' Basque form of Roman Germanus, meaning "brother."
KIMETZ, name: ' Basque name meaning "sprout."
KERBASI, name: ' Basque name meaning "warrior."
KOLDO, name: ' Nickname for Basque Koldobika, meaning "famous warrior."
KOLDOBIKA, name: ' Basque form of French Louis, meaning "famous warrior."
LAURENDI, name: ' Basque form of Laurence, meaning "of Laurentum."
LAURENTZI, name: ' Basque form of Laurence, meaning "of Laurentum."
LEHOI, name: ' Basque name meaning "Lion."
LER, name: ' Basque name meaning "pine."
LERTXUN, name: ' Basque name meaning "aspen."
LIHER, name: ' Masculine form of Basque Liernia, the patron saint of mothers without milk or who are unable to conceive.
LIZAR, name: ' Basque name meaning "ash."
LIZARDI, name: ' Basque name meaning "ash tree grove."
LON, name: ' Basque form of Leon, meaning "lion."
LORE, name: ' Basque unisex name meaning "flower."
LUIX, name: ' Basque form of Luis, meaning "famous warrior."
LUKEN, name: ' Basque form of Roman Lucianus, meaning "light."
LUZEA, name: ' Basque name meaning "long."
MARKEL, name: ' Basque form of Roman Martialis, meaning "of Mars."
MARKO, name: ' Basque, Bulgarian, and Ukrainian form of Latin Mark, meaning "warlike."
MARTZEL, name: ' Basque form of Roman Marcellus, meaning "warlike."
MARZ, name: ' Basque form of Latin Mark, meaning "warlike."
MATIA, name: ' Basque form of Matthew, meaning "gift of God."
MATTIN, name: ' Basque form of Latin Martinus, meaning "of/like Mars."
MATXIN, name: ' Basque form of Latin Martinus, meaning "of/like Mars."
MENDEBAL, name: ' Basque name meaning "west."
MIKEL, name: ' Basque form of Michael, meaning "who is like God?"
MITXEL, name: ' Basque form of Michael, meaning "who is like God?"
NIKOLA, name: ' Basque, Bulgarian and Hungarian form of Nicholas, meaning "victory of the people."
ODOL, name: ' Basque name meaning "blood."
ORKATZ, name: ' Basque name meaning "deer."
OROITZ, name: ' Basque name meaning "memory."
ORTLE, name: ' Basque name meaning "firmament."
ORTZI, name: ' Basque name meaning "sky."
OSKARBI, name: ' Basque name meaning "clear sky."
OSTADAR, name: ' Basque name meaning "rainbow."
OSTARGI, name: ' Basque name meaning "aurora."
OSTOTS, name: ' Basque name meaning "thunder."
OTSOA, name: ' Basque name meaning "wolf."
OTSOKO, name: ' Basque name meaning "wolf cub."
PANTZESKA, name: ' Basque form of Latin Franciscus, meaning "free."
PATXI, name: ' Pet form of Basque Pantzeska, meaning "free."
PAULIN, name: ' Basque form of Paul, meaning "small."
PAULO, name: ' Basque form of Paul, meaning "small."
PEIO, name: ' Basque form of Peter, meaning "rock; stone."
PELI, name: ' Basque form of Felix, meaning "lucky."
PERU, name: ' Basque form of Peter, meaning "rock; stone."
PETRI, name: ' Basque form of Peter, meaning "rock; stone."
SALBATORE, name: ' Basque name meaning "savior."
SANTUTXO, name: ' Basque name meaning "little saint."
SEME, name: ' Basque name meaning "son."
SENDOA, name: ' Basque name meaning "strong."
SU, name: ' Basque name meaning "fire."
TEOBALDO, name: ' Basque form of Theobald, meaning "people-bold."
TIBALT, name: ' Basque form of Theobald, meaning "people-bold."
TIPI, name: ' Basque name meaning "small."
TODOR, name: ' Basque form of Theodore, meaning "gift of God."
TUBAL, name: ' Biblical name of a son of Japheth, and possibly the ancestor of the Basques (see Aitor).
TXATXU, name: ' Basque name meaning "foolish."
TXERU, name: ' Basque name meaning "sky."
TXILAR, name: ' Basque name meaning "heather."
TXOMIN, name: ' Basque form of English Dominic, meaning "belongs to the lord."
UHIN, name: ' Basque name meaning "ocean wave."
UMEA, name: ' Basque name meaning "child."
UNAI, name: ' Basque name meaning "shepherd."
UR, name: ' Basque name meaning "water."
URDIN, name: ' Basque name meaning "blue."
URKI, name: ' Basque name meaning "birch tree."
URRE, name: ' Basque name meaning "gold."
XABIER, name: ' Basque and Galician form of English Xavier, meaning "a new house."
XALBADOR, name: ' Basque name meaning "savior."
XANTI, name: ' Basque form of Spanish Santiago, meaning "Saint Iago."
XARLES, name: ' Basque form of Charles, meaning "man."
XIMON, name: ' Variant of Basque Ximun, meaning "hearkening."
XIMUN, name: ' Basque form of Greek Simon, meaning "hearkening."
YULI, name: ' Basque name meaning "youthful."
ZERU, name: ' Basque name meaning "sky."
ZIGOR, name: ' Basque name meaning "punishment."
ZILAR, name: ' Basque name meaning "silver."
ZORION, name: ' Basque unisex name meaning "happiness."
ZUHAITZ, name: ' Basque unisex name meaning "tree."
ZUMAR, name: ' Basque name meaning "elm."
ZURI, name: ' Basque name meaning "white."
ZUZEN, name: ' Basque name meaning "fair, just."
]